package com.example.data.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.example.domain.model.DownloadItem
import com.example.domain.model.DownloadStatus
import com.example.domain.model.LyricsData
import com.example.domain.model.LyricsLine
import com.example.domain.model.LyricsProvider
import androidx.room.Index
import com.example.domain.model.LocalStorageState
import com.example.domain.model.Track

@Entity(
    tableName = "tracks",
    indices = [
        Index(value = ["offlineAvailable"]),
        Index(value = ["isLiked"]),
        Index(value = ["isDownloaded"]),
        Index(value = ["localFilePath"])
    ]
)
data class TrackEntity(
    @PrimaryKey val id: String,
    val title: String,
    val artist: String,
    val artistId: String = "",
    val album: String = "",
    val albumId: String = "",
    val durationSeconds: Long = 0,
    val artworkUrl: String = "",
    val streamUrl: String = "",
    val isLiked: Boolean = false,
    val isDownloaded: Boolean = false,
    val isCached: Boolean = false,
    val localFilePath: String? = null,
    val storageState: String = "ONLINE_ONLY",
    val fileSizeBytes: Long = 0,
    val mimeType: String = "audio/mp4",
    val offlineAvailable: Boolean = false,
    val playCount: Long = 0,
    val lastPlayedAt: Long = 0,
    val cachedAt: Long = 0,
    val dateAdded: Long = System.currentTimeMillis()
) {
    fun toDomain(): Track = Track(
        id = id,
        title = title,
        artist = artist,
        artistId = artistId,
        album = album,
        albumId = albumId,
        durationSeconds = durationSeconds,
        artworkUrl = artworkUrl,
        streamUrl = streamUrl,
        isLiked = isLiked,
        isDownloaded = isDownloaded,
        isCached = isCached,
        localFilePath = localFilePath,
        storageState = runCatching { LocalStorageState.valueOf(storageState) }
            .getOrDefault(LocalStorageState.ONLINE_ONLY),
        fileSizeBytes = fileSizeBytes,
        mimeType = mimeType,
        offlineAvailable = offlineAvailable,
        playCount = playCount,
        lastPlayedAt = lastPlayedAt,
        cachedAt = cachedAt,
        dateAdded = dateAdded
    )

    companion object {
        fun fromDomain(track: Track): TrackEntity = TrackEntity(
            id = track.id,
            title = track.title,
            artist = track.artist,
            artistId = track.artistId,
            album = track.album,
            albumId = track.albumId,
            durationSeconds = track.durationSeconds,
            artworkUrl = track.artworkUrl,
            streamUrl = track.streamUrl,
            isLiked = track.isLiked,
            isDownloaded = track.isDownloaded,
            isCached = track.isCached,
            localFilePath = track.localFilePath,
            storageState = track.storageState.name,
            fileSizeBytes = track.fileSizeBytes,
            mimeType = track.mimeType,
            offlineAvailable = track.offlineAvailable,
            playCount = track.playCount,
            lastPlayedAt = track.lastPlayedAt,
            cachedAt = track.cachedAt,
            dateAdded = track.dateAdded
        )
    }
}

@Entity(tableName = "playlists")
data class PlaylistEntity(
    @PrimaryKey val id: String,
    val title: String,
    val description: String = "",
    val coverUrl: String = "",
    val isAutoGenerated: Boolean = false,
    val createdAt: Long = System.currentTimeMillis()
)

@Entity(tableName = "playlist_tracks", primaryKeys = ["playlistId", "trackId"])
data class PlaylistTrackCrossRef(
    val playlistId: String,
    val trackId: String,
    val orderIndex: Int = 0
)

@Entity(tableName = "downloads")
data class DownloadEntity(
    @PrimaryKey val trackId: String,
    val trackTitle: String,
    val artist: String,
    val artworkUrl: String,
    val progress: Float,
    val status: String,
    val totalBytes: Long,
    val downloadedBytes: Long,
    val localPath: String?
) {
    fun toDomain(): DownloadItem = DownloadItem(
        trackId = trackId,
        trackTitle = trackTitle,
        artist = artist,
        artworkUrl = artworkUrl,
        progress = progress,
        status = runCatching { DownloadStatus.valueOf(status) }.getOrDefault(DownloadStatus.QUEUED),
        totalBytes = totalBytes,
        downloadedBytes = downloadedBytes,
        localPath = localPath
    )

    companion object {
        fun fromDomain(item: DownloadItem): DownloadEntity = DownloadEntity(
            trackId = item.trackId,
            trackTitle = item.trackTitle,
            artist = item.artist,
            artworkUrl = item.artworkUrl,
            progress = item.progress,
            status = item.status.name,
            totalBytes = item.totalBytes,
            downloadedBytes = item.downloadedBytes,
            localPath = item.localPath
        )
    }
}

@Entity(tableName = "lyrics_cache")
data class LyricsCacheEntity(
    @PrimaryKey val trackId: String,
    val provider: String,
    val isSynced: Boolean,
    val serializedLines: String,
    val plainLyrics: String,
    val cachedAt: Long = System.currentTimeMillis()
) {
    fun toDomain(): LyricsData {
        val lines = if (serializedLines.isNotBlank()) {
            serializedLines.split("\n--LINE--\n").mapNotNull { lineStr ->
                val parts = lineStr.split("|||")
                if (parts.size >= 2) {
                    val time = parts[0].toLongOrNull() ?: 0L
                    val text = parts[1]
                    val trans = if (parts.size > 2 && parts[2].isNotBlank()) parts[2] else null
                    LyricsLine(timeMs = time, text = text, translation = trans)
                } else null
            }
        } else emptyList()

        return LyricsData(
            trackId = trackId,
            lines = lines,
            isSynced = isSynced,
            provider = runCatching { LyricsProvider.valueOf(provider) }.getOrDefault(LyricsProvider.OFFLINE_CACHE),
            plainLyrics = plainLyrics
        )
    }

    companion object {
        fun fromDomain(lyrics: LyricsData): LyricsCacheEntity {
            val serialized = lyrics.lines.joinToString("\n--LINE--\n") { line ->
                "${line.timeMs}|||${line.text}|||${line.translation ?: ""}"
            }
            return LyricsCacheEntity(
                trackId = lyrics.trackId,
                provider = lyrics.provider.name,
                isSynced = lyrics.isSynced,
                serializedLines = serialized,
                plainLyrics = lyrics.plainLyrics
            )
        }
    }
}

@Entity(tableName = "history")
data class HistoryEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val trackId: String,
    val title: String,
    val artist: String,
    val artworkUrl: String,
    val playedAt: Long = System.currentTimeMillis()
)
