package com.example.data.repository

import android.net.Uri
import com.example.core.audio.AudioRecognitionManager
import com.example.data.cache.CacheManager
import com.example.data.download.DownloadManager
import com.example.data.innertube.InnerTubeClient
import com.example.data.lastfm.LastFmService
import com.example.data.local.LocalMediaScanner
import com.example.data.local.VmusixDatabase
import com.example.data.local.entities.HistoryEntity
import com.example.data.local.entities.PlaylistEntity
import com.example.data.local.entities.PlaylistTrackCrossRef
import com.example.data.local.entities.TrackEntity
import com.example.data.lyrics.LyricsService
import com.example.domain.model.Album
import com.example.domain.model.Artist
import com.example.domain.model.LocalStorageState
import com.example.domain.model.LyricsData
import com.example.domain.model.Playlist
import com.example.domain.model.Track
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map

class MusicRepository(
    val database: VmusixDatabase,
    val innerTubeClient: InnerTubeClient,
    val lyricsService: LyricsService,
    val downloadManager: DownloadManager,
    val cacheManager: CacheManager,
    val lastFmService: LastFmService,
    val audioRecognitionManager: AudioRecognitionManager,
    val localMediaScanner: LocalMediaScanner,
    val trackCacheRepository: TrackCacheRepository
) {
    val likedTracks: Flow<List<Track>> = database.trackDao().getLikedTracks().map { list ->
        list.map { it.toDomain() }
    }

    val downloadedTracks: Flow<List<Track>> = trackCacheRepository.downloadedTracks

    val cachedTracks: Flow<List<Track>> = trackCacheRepository.cachedTracks

    val allOfflineTracks: Flow<List<Track>> = trackCacheRepository.allOfflineTracks

    val allLibraryTracks: Flow<List<Track>> = database.trackDao().getAllLibraryTracks().map { list ->
        list.map { it.toDomain() }
    }

    val uploadedAndLocalTracks: Flow<List<Track>> = database.trackDao().getUploadedAndLocalTracks().map { list ->
        list.map { it.toDomain() }
    }

    val playlists: Flow<List<Playlist>> = database.playlistDao().getAllPlaylists().map { list ->
        list.map {
            Playlist(
                id = it.id,
                title = it.title,
                description = it.description,
                coverUrl = it.coverUrl,
                isAutoGenerated = it.isAutoGenerated
            )
        }
    }

    val recentHistory: Flow<List<Track>> = database.historyDao().getRecentHistory().map { list ->
        list.map {
            Track(
                id = it.trackId,
                title = it.title,
                artist = it.artist,
                artworkUrl = it.artworkUrl
            )
        }
    }

    suspend fun loadAllLibraryMusic(): List<Track> {
        val scanned = localMediaScanner.scanDeviceMediaStore()
        val presets = localMediaScanner.loadPresetLibraryTracks()
        val combined = (scanned + presets).distinctBy { it.id }
        database.trackDao().insertAll(combined.map { TrackEntity.fromDomain(it) })
        return combined
    }

    suspend fun importAudioUris(uris: List<Uri>): List<Track> {
        val imported = localMediaScanner.importAudioUris(uris)
        if (imported.isNotEmpty()) {
            database.trackDao().insertAll(imported.map { TrackEntity.fromDomain(it) })
        }
        return imported
    }

    suspend fun cacheTrackForOffline(track: Track, localFilePath: String, fileSizeBytes: Long): Track {
        return trackCacheRepository.cacheTrackForOffline(track, localFilePath, fileSizeBytes)
    }

    suspend fun isTrackOfflineReady(trackId: String): Boolean {
        return trackCacheRepository.isTrackOfflineReady(trackId)
    }

    suspend fun getTrackForPlayback(trackId: String): Track? {
        return trackCacheRepository.getTrackForPlayback(trackId)
    }

    suspend fun removeOfflineStorage(trackId: String): Boolean {
        return trackCacheRepository.removeOfflineCache(trackId)
    }

    suspend fun getQuickPicks(): List<Track> = innerTubeClient.getQuickPicks()
    suspend fun getTrending(): List<Track> = innerTubeClient.getTrending()
    suspend fun getRecommended(): List<Track> = innerTubeClient.getRecommended()
    suspend fun getNewReleases(): List<Album> = innerTubeClient.getNewReleases()
    suspend fun getFavoriteArtists(): List<Artist> = innerTubeClient.getFavoriteArtists()
    suspend fun getTop50(): List<Track> = innerTubeClient.getTop50Charts()

    suspend fun search(query: String, filter: String = "ALL"): List<Track> =
        innerTubeClient.search(query, filter)

    suspend fun toggleLike(track: Track) {
        val newLiked = !track.isLiked
        database.trackDao().insertOrUpdate(TrackEntity.fromDomain(track.copy(isLiked = newLiked)))
        database.trackDao().setLiked(track.id, newLiked)
    }

    suspend fun isTrackLiked(trackId: String): Boolean {
        return database.trackDao().getTrackById(trackId)?.isLiked ?: false
    }

    suspend fun recordHistory(track: Track) {
        database.historyDao().insertHistory(
            HistoryEntity(
                trackId = track.id,
                title = track.title,
                artist = track.artist,
                artworkUrl = track.artworkUrl
            )
        )
        database.trackDao().incrementPlayCount(track.id)
        cacheManager.autoCacheTrack(track)
        lastFmService.scrobbleTrack(track)
    }

    suspend fun getLyrics(track: Track): LyricsData {
        return lyricsService.getLyrics(track)
    }

    suspend fun createPlaylist(title: String, description: String = ""): String {
        val id = "pl_${System.currentTimeMillis()}"
        database.playlistDao().insertPlaylist(
            PlaylistEntity(
                id = id,
                title = title,
                description = description,
                coverUrl = "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80"
            )
        )
        return id
    }

    suspend fun addTrackToPlaylist(playlistId: String, track: Track) {
        database.trackDao().insertOrUpdate(TrackEntity.fromDomain(track))
        database.playlistDao().addTrackToPlaylist(
            PlaylistTrackCrossRef(playlistId = playlistId, trackId = track.id)
        )
    }

    fun getPlaylistTracks(playlistId: String): Flow<List<Track>> {
        return database.playlistDao().getTracksForPlaylist(playlistId).map { list ->
            list.map { it.toDomain() }
        }
    }
}
