package com.example.domain.model

enum class LocalStorageState {
    ONLINE_ONLY,
    CACHED_STREAM,
    DOWNLOADED,
    LOCAL_DEVICE
}

data class Track(
    val id: String,
    val title: String,
    val artist: String,
    val artistId: String = "",
    val album: String = "",
    val albumId: String = "",
    val durationSeconds: Long = 0,
    val artworkUrl: String = "",
    val streamUrl: String = "",
    val isLiked: Boolean = false,
    val isDownloaded: Boolean = false,
    val isCached: Boolean = false,
    val localFilePath: String? = null,
    val storageState: LocalStorageState = when {
        localFilePath?.startsWith("content://") == true -> LocalStorageState.LOCAL_DEVICE
        isDownloaded -> LocalStorageState.DOWNLOADED
        isCached -> LocalStorageState.CACHED_STREAM
        else -> LocalStorageState.ONLINE_ONLY
    },
    val fileSizeBytes: Long = 0,
    val mimeType: String = "audio/mp4",
    val offlineAvailable: Boolean = isDownloaded || isCached || (localFilePath != null),
    val playCount: Long = 0,
    val lastPlayedAt: Long = 0,
    val cachedAt: Long = 0,
    val dateAdded: Long = System.currentTimeMillis()
) {
    val durationFormatted: String
        get() {
            val minutes = durationSeconds / 60
            val seconds = durationSeconds % 60
            return "%d:%02d".format(minutes, seconds)
        }

    val isPlayableOffline: Boolean
        get() = offlineAvailable && !localFilePath.isNullOrBlank()
}

data class Artist(
    val id: String,
    val name: String,
    val imageUrl: String = "",
    val monthlyListeners: String = "",
    val topTracks: List<Track> = emptyList()
)

data class Album(
    val id: String,
    val title: String,
    val artist: String,
    val year: String = "",
    val coverUrl: String = "",
    val tracks: List<Track> = emptyList()
)

data class Playlist(
    val id: String,
    val title: String,
    val description: String = "",
    val coverUrl: String = "",
    val trackCount: Int = 0,
    val isAutoGenerated: Boolean = false,
    val tracks: List<Track> = emptyList()
)

enum class DownloadStatus {
    QUEUED, DOWNLOADING, PAUSED, COMPLETED, FAILED
}

data class DownloadItem(
    val trackId: String,
    val trackTitle: String,
    val artist: String,
    val artworkUrl: String,
    val progress: Float = 0f,
    val status: DownloadStatus = DownloadStatus.QUEUED,
    val totalBytes: Long = 0,
    val downloadedBytes: Long = 0,
    val localPath: String? = null
)
